
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
#    ports:
#      - '3001:3001'
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_ENDPOINT_URL=${NEXT_PUBLIC_ENDPOINT_URL}
      - NEXT_PUBLIC_AWS_REGION=${NEXT_PUBLIC_AWS_REGION}
      - NEXT_PUBLIC_AWS_S3_BUCKET_NAME=${NEXT_PUBLIC_AWS_S3_BUCKET_NAME}
      - NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - GITHUBS_CLIENT_ID=${GITHUBS_CLIENT_ID}
      - GITHUBS_CLIENT_SECRET=${GITHUBS_CLIENT_SECRET}
      - GITHUBS_CALLBACK_URL=${GITHUBS_CALLBACK_URL}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
      - TWITTER_CALLBACK_URL=${TWITTER_CALLBACK_URL}
      - STRIPE_KEY=${STRIPE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - BROWSERLESS_ENDPOINT=${BROWSERLESS_ENDPOINT}
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_ENDPOINT_URL: ${NEXT_PUBLIC_ENDPOINT_URL}
        NEXT_PUBLIC_AWS_REGION: ${NEXT_PUBLIC_AWS_REGION}
        NEXT_PUBLIC_AWS_S3_BUCKET_NAME: ${NEXT_PUBLIC_AWS_S3_BUCKET_NAME}
        NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
#    ports:
#      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_ENDPOINT_URL=${NEXT_PUBLIC_ENDPOINT_URL}
      - NEXT_PUBLIC_AWS_REGION=${NEXT_PUBLIC_AWS_REGION}
      - NEXT_PUBLIC_AWS_S3_BUCKET_NAME=${NEXT_PUBLIC_AWS_S3_BUCKET_NAME}
      - NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
    depends_on:
      - api
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
    networks:
      - app-network

  postgres:
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
